set(CMAKE_CXX_COMPILER clang++ CACHE STRING "C++ compiler")
set(CMAKE_CXX_FLAGS_INIT "-stdlib=libc++")
get_filename_component(_project_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(libcxx_root "${_project_root}/.deps/libcxx/usr" CACHE PATH "Optional local libc++ prefix")
if(EXISTS "${libcxx_root}/include/c++/v1/vector")
  string(APPEND CMAKE_CXX_FLAGS_INIT " -nostdinc++ -Wno-unused-command-line-argument -isystem ${libcxx_root}/include/c++/v1")
  set(CMAKE_EXE_LINKER_FLAGS_INIT "-L${libcxx_root}/lib -Wl,-rpath,${libcxx_root}/lib")
endif()
