set(filament_root "${CMAKE_CURRENT_LIST_DIR}/../.deps/filament" CACHE PATH "Matching Filament 1.77.1 native SDK and tools")
if(NOT EXISTS "${filament_root}/include/filament/Engine.h")
  message(FATAL_ERROR "Filament SDK missing. Run tools/fetch_filament.sh or set filament_root.")
endif()
if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  message(FATAL_ERROR "The official Filament SDK uses libc++. Configure this build with Clang and libc++.")
endif()
find_package(Threads REQUIRED)
set(_filament_libdir "${filament_root}/lib/x86_64")
if(APPLE)
  set(_filament_libdir "${filament_root}/lib/arm64")
  if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
    set(_filament_libdir "${filament_root}/lib/x86_64")
  endif()
endif()
set(_filament_libraries)
foreach(lib gltfio_core uberarchive uberzlib filament-iblprefilter filament-generatePrefilterMipmap filament backend filabridge filaflat utils geometry smol-v bluegl bluevk shaders dracodec meshoptimizer basis_transcoder stb zstd abseil)
  if(EXISTS "${_filament_libdir}/lib${lib}.a")
    list(APPEND _filament_libraries "${_filament_libdir}/lib${lib}.a")
  endif()
endforeach()
add_library(sengine::filament INTERFACE IMPORTED GLOBAL)
target_include_directories(sengine::filament SYSTEM INTERFACE "${filament_root}/include")
if(APPLE)
  target_link_libraries(sengine::filament INTERFACE ${_filament_libraries} "-framework Cocoa" "-framework Metal" "-framework QuartzCore" "-framework CoreVideo")
else()
  target_link_libraries(sengine::filament INTERFACE "$<LINK_GROUP:RESCAN,${_filament_libraries}>" c++abi dl)
endif()
